//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by Fernflower decompiler)
//

public class Card_Constructor {
    public static Treasure[] TreasureCards = new Treasure[]{new Treasure("Boots of Running Really Fast", 0, 400, "Human", (String)null, "Shoes", (String)null), new Treasure("Spiky Knees", 1, 200, (String)null, "Human", "", (String)null), new Treasure("Staff of Napalm", 5, 800, "Human", "Wizard", "1 Hand", (String)null), new Treasure("Stepladder", 3, 400, "Halfling", (String)null, "", (String)null), new Treasure("Swiss Army Polearm", 4, 600, "Human", (String)null, "2 Hand", (String)null), new Treasure("Flaming Armor", 2, 400, "Human", (String)null, "Armour", (String)null), new Treasure("Club", 3, 400, "Human", (String)null, "1 Hand", (String)null), new Treasure("Hammer of Kneecap", 4, 600, "Dwarf", (String)null, "1 Hand", (String)null), new Treasure("Helm of Courage", 1, 200, "Human", (String)null, "Helmet", (String)null), new Treasure("Huge Rock", 3, 0, "Human", (String)null, "2 Hand", (String)null), new Treasure("Leather Armor", 1, 200, "Human", (String)null, "Armour", (String)null), new Treasure("Stincky Sandwich", 3, 400, "Halfling", (String)null, "Regular", (String)null), new Treasure("Mace of Sharpness", 4, 600, "Human", "Cliric", "1 Hand", (String)null), new Treasure("Mithryl Armor", 3, 600, "Human", "!Wizards", "Armor", (String)null), new Treasure("Bad Ass Bandana", 3, 400, "Human", (String)null, "Armor", (String)null), new Treasure("Boots of Butt-Kicking", 2, 400, "Human", (String)null, "Shoes", (String)null), new Treasure("Bow with Ribbons", 4, 800, "Elf", (String)null, "2 Hand", (String)null), new Treasure("Broad Sword", 3, 400, "Human", (String)null, "1 Hand", (String)null), new Treasure("Buckler of Swasher", 2, 400, "Human", (String)null, "1 Hand", (String)null), new Treasure("Chainsaw of Bloody Dismemberment", 3, 600, "Human", (String)null, "2 Hand", (String)null), new Treasure("Cheese Grater of Peace", 3, 400, "Human", "Cliric", "1 Hand", (String)null), new Treasure("Cloak of Obcsurity", 4, 600, "Human", "Thieves", "Regular", (String)null), new Treasure("Dagger of Treachery", 3, 400, "Human", "Thieves", "1 Hand", (String)null), new Treasure("Eleven-Foot Pole", 1, 200, "Human", (String)null, "2 Hand", (String)null)};
    public Monster[] Monster = new Monster[]{new Monster("Young Rat", 1, 1, 1, 0, (String)null), new Monster("Mr.Bones", 2, 1, 2, 0, (String)null), new Monster("Snails on Speed", 4, 1, 0, -2, (String)null), new Monster("Screaming Gekk", 6, 2, 0, 0, (String)null), new Monster("Potter_Plant", 1, 1, 0, 0, (String)null), new Monster("3875 Orks", 10, 3, 0, 0, (String)null), new Monster("Amazon", 8, 2, 0, 0, (String)null), new Monster("Big Foot", 12, 3, 0, 0, (String)null), new Monster("Bull Rog", 18, 5, 2, 0, (String)null), new Monster("Crabs", 1, 1, 0, 0, (String)null), new Monster("Drooling Slime", 1, 1, 0, 0, (String)null), new Monster("Face Sucker", 8, 2, 0, 0, (String)null), new Monster("Floating Monster", 10, 3, 3, -4, (String)null), new Monster("Flyting Frogs", 2, 1, 2, -1, (String)null), new Monster("Gazebo", 8, 2, 3, 0, (String)null), new Monster("Gelatinous Octahedron", 2, 1, 0, 1, (String)null), new Monster("Ghoul Fiends", 8, 2, 1, 0, (String)null), new Monster("Harpies", 4, 2, 2, 0, (String)null), new Monster("Hippogrief", 16, 4, 2, 0, (String)null), new Monster("Insurance Salesman", 14, 4, 0, 0, (String)null), new Monster("King Tut", 16, 4, 2, 0, (String)null), new Monster("Lame Goblin", 1, 1, 1, 1, (String)null), new Monster("Large Angry Chicken", 2, 1, 1, 0, (String)null), new Monster("Lawyers", 6, 2, 0, 0, (String)null), new Monster("Leperchaun", 4, 2, 0, 0, (String)null)};

    public Card_Constructor() {
    }
}
